### ISSUE TITLE
What version of OpenCV did you use to compile

### ISSUE THREAD

**Issue by juancgalvez** [rmcqueen/traffic-monitor#6]
Hi.

I am trying to compile with OpenCV 4.3-dev and I am getting all these errors:

`[ 26%] Building CXX object CMakeFiles/traffic-monitor.dir/src/AppConfig.cpp.o
/home/pi/traffic-monitor/src/AppConfig.cpp: In member function 'void AppConfig::run()':
/home/pi/traffic-monitor/src/AppConfig.cpp:157:44: error: 'CV_FOURCC' was not declared in this scope
   cv::VideoWriter out_video("output.h264", CV_FOURCC('H', '2', '6', '4'), 30, cv::Size(640, 480));
                                            ^~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:157:44: note: suggested alternative: 'CV_16UC'
   cv::VideoWriter out_video("output.h264", CV_FOURCC('H', '2', '6', '4'), 30, cv::Size(640, 480));
                                            ^~~~~~~~~
                                            CV_16UC
/home/pi/traffic-monitor/src/AppConfig.cpp:171:16: error: 'CV_CAP_PROP_FPS' was not declared in this scope
   capVideo.set(CV_CAP_PROP_FPS, get_FPS());
                ^~~~~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:171:16: note: suggested alternative: 'CV_CPU_POPCNT'
   capVideo.set(CV_CAP_PROP_FPS, get_FPS());
                ^~~~~~~~~~~~~~~
                CV_CPU_POPCNT
/home/pi/traffic-monitor/src/AppConfig.cpp:172:16: error: 'CV_CAP_PROP_FRAME_WIDTH' was not declared in this scope
   capVideo.set(CV_CAP_PROP_FRAME_WIDTH, get_FRAME_WIDTH());
                ^~~~~~~~~~~~~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:172:16: note: suggested alternative: 'get_FRAME_WIDTH'
   capVideo.set(CV_CAP_PROP_FRAME_WIDTH, get_FRAME_WIDTH());
                ^~~~~~~~~~~~~~~~~~~~~~~
                get_FRAME_WIDTH
/home/pi/traffic-monitor/src/AppConfig.cpp:173:16: error: 'CV_CAP_PROP_FRAME_HEIGHT' was not declared in this scope
   capVideo.set(CV_CAP_PROP_FRAME_HEIGHT, get_FRAME_HEIGHT());
                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:173:16: note: suggested alternative: 'get_FRAME_HEIGHT'
   capVideo.set(CV_CAP_PROP_FRAME_HEIGHT, get_FRAME_HEIGHT());
                ^~~~~~~~~~~~~~~~~~~~~~~~
                get_FRAME_HEIGHT
/home/pi/traffic-monitor/src/AppConfig.cpp:245:55: error: 'CV_RETR_TREE' was not declared in this scope
     cv::findContours(img_thresh, contours, hierarchy, CV_RETR_TREE, CV_CHAIN_APPROX_SIMPLE, cv::Point(0, 0));
                                                       ^~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:245:55: note: suggested alternative: 'CV_MAT_TYPE'
     cv::findContours(img_thresh, contours, hierarchy, CV_RETR_TREE, CV_CHAIN_APPROX_SIMPLE, cv::Point(0, 0));
                                                       ^~~~~~~~~~~~
                                                       CV_MAT_TYPE
/home/pi/traffic-monitor/src/AppConfig.cpp:245:69: error: 'CV_CHAIN_APPROX_SIMPLE' was not declared in this scope
     cv::findContours(img_thresh, contours, hierarchy, CV_RETR_TREE, CV_CHAIN_APPROX_SIMPLE, cv::Point(0, 0));
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:299:39: error: 'CV_CAP_PROP_POS_FRAMES' was not declared in this scope
     if (!live_capture && capVideo.get(CV_CAP_PROP_POS_FRAMES) == capVideo.get(CV_CAP_PROP_FRAME_COUNT)) {
                                       ^~~~~~~~~~~~~~~~~~~~~~
/home/pi/traffic-monitor/src/AppConfig.cpp:299:79: error: 'CV_CAP_PROP_FRAME_COUNT' was not declared in this scope
     if (!live_capture && capVideo.get(CV_CAP_PROP_POS_FRAMES) == capVideo.get(CV_CAP_PROP_FRAME_COUNT)) {
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/traffic-monitor.dir/build.make:63: CMakeFiles/traffic-monitor.dir/src/AppConfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/traffic-monitor.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

Sorry about bad formatting. I used code formatting but doesn't work well.

**Comment by rmcqueen** [comment]
Hi, thanks for filing this issue. I was using OpenCV v4.0.0 for this project. I'll update the README.

**Comment by rmcqueen** [comment]
Fixed in https://github.com/rmcqueen/traffic-monitor/commit/fd588a603b0faaf5d5de51dc0d637d2cba9a1d5a.

**Comment by juancgalvez** [comment]
Thank you for your reply. I will try that.
